"""
Program:        check-ai.py
Description:    Checks to see if CRNs generated by Google AI match CRNs in the CSV file (if the classes exist).
Last updated:   6/30/2025
"""

import google.generativeai as genai
import re
import mysql.connector

AI_TOKEN = "AIzaSyBGbEWPMhNbY51m5m884LGrWV-CvbdLKKE"
genai.configure(api_key=AI_TOKEN)

conn = mysql.connector.connect(
    host = "XXX.X.X.X",
    user = "root",
    password = "XXXX",
    database = "courses"
)
cursor = conn.cursor()

model = genai.GenerativeModel('gemini-2.5-pro')

valid_crns = "CRN 75291"

for thing in re.findall(r"CRN (\d+)", valid_crns):
    CRN = int(thing)
    cursor.execute("SELECT courseReferenceNumber FROM courses_table WHERE courseReferenceNumber = %s", (CRN,))
    rows = cursor.fetchall()
    if not rows:
        print(f"CRN {CRN} not found in the database.")

cursor.close()
conn.close()
